#!/usr/bin/bash
clear
echo
echo -e '\e[1;35m'
figlet -f slant Install
echo
echo -e '\e[1;31m' '============================================================='
echo -e '\e[1;36m' "Author      = ALX-04 ^_<"
echo -e '\e[1;36m' "Team        = INDONESIAN ERROR SYSTEM"
echo -e '\e[1;36m' "Facebook    = Aldi Linalda"  
echo -e '\e[1;36m' "Email       = aldilinalda12@gmail.com"     
echo -e '\e[1;34m' "                        GRETS TO:  
 Mr.:/R1zK1 | CIPPEL | r1c3-4 | AMRiezZ | Mr.BL4NGK0N4N | 
 M4RV3L-23 | IRFAN |N4ST4R_ID | UKHWAH ISLAMIYAH | 
 Mr.3V0LUT10N | BITCHIS | BOY NAINGGOLAN | And ALL MEMBER "
echo -e '\e[1;31m' '============================================================='
echo
toilet -f mono12 -F gay install | lolcat
echo -e "[1]install"
read -p "Tekan 1 =" act;
if [ $act = 1 ]
then
echo -e '\e[1;33m' "..............Loading..............."
cp i.cow /data/data/com.termux/files/usr/share/cows/
cp e.cow /data/data/com.termux/files/usr/share/cows/
cp s.cow /data/data/com.termux/files/usr/share/cows/
echo -e '\e[1;33m' "---------------DONE--------------"
exit
fi

